In [1]:
!pip install numpy


Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

In [3]:
lst = [1,2,3,4,5]

In [4]:
arr = np.array(lst)

In [5]:
type(arr)

numpy.ndarray

In [9]:
twoByThree = np.array([[1,2,3],[4,5,6]])

In [10]:
twoByThree


array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
threeByTwo =twoByThree.reshape(3,2)

In [12]:
threeByTwo


array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
np.random.rand(4,5)

array([[0.10414887, 0.22433869, 0.40975903, 0.69437823, 0.6433907 ],
       [0.24315018, 0.77156666, 0.0618901 , 0.33813585, 0.75945819],
       [0.93191438, 0.74333533, 0.78124025, 0.74994313, 0.35891221],
       [0.16246185, 0.05656994, 0.97255477, 0.10309421, 0.93473639]])

In [14]:
np.random.randn(4,5)

array([[-0.40880871, -1.45214448,  0.31692579, -0.68302456, -1.30419607],
       [ 0.50751138, -2.25603066, -0.27720726,  0.46501108, -0.33571197],
       [-0.17074881, -0.70948505, -0.16674368,  2.06534339,  1.02693343],
       [-0.44687428,  1.32204269,  0.54581657, -0.86107594,  0.3177162 ]])

In [15]:
np.random.randint(0,100)

59

In [21]:
np.random.randint(0,100,5)

array([ 0, 54, 90, 47, 92])

In [49]:
np.random.randint(0,100,20).reshape(4,5)

array([[51, 59, 61, 29,  5],
       [39, 17, 15, 10,  2],
       [ 3, 36, 13,  9, 38],
       [ 4, 36, 80,  4, 38]])

In [20]:
np.random.randint(0,100,(4,5))

array([[98, 94, 53, 83, 49],
       [56, 31, 26, 27, 48],
       [ 7, 20, 89, 25, 22],
       [33, 34, 45, 83,  6]])

In [30]:
zeroToNineArr = np.arange(0,10)


In [31]:
zeroToNineArr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
zeroToNineArr[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
zeroToNineArr[:6]

array([0, 1, 2, 3, 4, 5])

In [34]:
zeroToNineArr[2:6]

array([2, 3, 4, 5])

In [35]:
zeroToNineArr[-4:]#last four

array([6, 7, 8, 9])

In [36]:
zeroToNineArr[1:-1]#skip first and last

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
zeroToNineArr[2:-2]#skip 2 elements from both end

array([2, 3, 4, 5, 6, 7])

In [42]:
zeroToNineArr[-1::-1]#start from last to first in -1 step

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [43]:
zeroToNineArr[9::-1]#same as above

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [45]:
zeroToNineArr[0::2]

array([0, 2, 4, 6, 8])

In [46]:
zeroToNineArr[-1::-2]

array([9, 7, 5, 3, 1])

In [50]:
fourByFive = np.random.randint(0,100,20).reshape(4,5)

In [51]:
fourByFive

array([[23, 74, 43, 97,  6],
       [84, 72, 50, 80, 59],
       [ 4, 83, 69, 12, 32],
       [81, 77, 44, 94, 61]])

In [52]:
fourByFive[2:3]

array([[ 4, 83, 69, 12, 32]])

In [53]:
fourByFive[2::,2::]

array([[69, 12, 32],
       [44, 94, 61]])

In [76]:
arr1=np.random.randint(1,10,(10,10))
arr2=np.random.randint(1,10,(3,3))

In [55]:
arr1+arr2

array([[ 2, 11, 15],
       [ 7, 16, 11],
       [16,  9, 15]])

In [57]:
arr1


array([[1, 6, 8],
       [2, 9, 2],
       [7, 7, 6]])

In [64]:
arr2

array([[1, 5, 7],
       [5, 7, 9],
       [9, 2, 9]])

In [59]:
arr1*arr2


array([[ 1, 30, 56],
       [10, 63, 18],
       [63, 14, 54]])

In [86]:
import pandas as pd

In [87]:
arr1=np.random.randint(1,10,(20,10))
df = pd.DataFrame(data=arr1)

In [62]:
df

0  1  2
0  1  6  8
1  2  9  2
2  7  7  6

In [69]:
df2 = pd.DataFrame(data=arr1*arr2)

In [70]:
df2

0   1   2
0   1  30  56
1  10  63  18
2  63  14  54

In [82]:
df = pd.DataFrame(data=arr1)
df

0  1  2  3  4  5  6  7  8  9
0  8  4  7  3  5  5  8  9  2  5
1  1  7  7  5  8  8  5  2  6  3
2  9  3  6  3  7  6  6  7  1  2
3  5  3  9  1  1  2  2  5  1  8
4  7  7  5  9  6  2  8  5  5  8
5  6  3  2  2  7  8  6  5  1  7
6  9  4  9  8  7  3  6  6  6  5
7  2  5  2  6  7  2  3  7  8  3
8  6  2  3  3  8  1  2  7  1  8
9  5  3  1  3  7  9  9  9  4  1

In [81]:
df.head()

0  1  2  3  4  5  6  7  8  9
0  8  4  7  3  5  5  8  9  2  5
1  1  7  7  5  8  8  5  2  6  3
2  9  3  6  3  7  6  6  7  1  2
3  5  3  9  1  1  2  2  5  1  8
4  7  7  5  9  6  2  8  5  5  8

In [83]:
df.head(2)

0  1  2  3  4  5  6  7  8  9
0  8  4  7  3  5  5  8  9  2  5
1  1  7  7  5  8  8  5  2  6  3

In [84]:
df.tail(3)

0  1  2  3  4  5  6  7  8  9
7  2  5  2  6  7  2  3  7  8  3
8  6  2  3  3  8  1  2  7  1  8
9  5  3  1  3  7  9  9  9  4  1

In [85]:
df.describe()

0         1          2          3          4          5  \
count  10.000000  10.00000  10.000000  10.000000  10.000000  10.000000   
mean    5.800000   4.10000   5.100000   4.300000   6.300000   4.600000   
std     2.699794   1.72884   2.960856   2.626785   2.057507   2.988868   
min     1.000000   2.00000   1.000000   1.000000   1.000000   1.000000   
25%     5.000000   3.00000   2.250000   3.000000   6.250000   2.000000   
50%     6.000000   3.50000   5.500000   3.000000   7.000000   4.000000   
75%     7.750000   4.75000   7.000000   5.750000   7.000000   7.500000   
max     9.000000   7.00000   9.000000   9.000000   8.000000   9.000000   

               6          7          8          9  
count  10.000000  10.000000  10.000000  10.000000  
mean    5.500000   6.200000   3.500000   5.000000  
std     2.505549   2.097618   2.635231   2.666667  
min     2.000000   2.000000   1.000000   1.000000  
25%     3.500000   5.000000   1.000000   3.000000  
50%     6.000000   6.500000   3.000000   5.000000  
75%     7.500000   7.000000   5.750000   7.750000  
max     9.000000   9.000000   8.000000   8.000000

In [89]:
df.describe()

0          1          2          3          4          5  \
count  20.000000  20.000000  20.000000  20.000000  20.000000  20.000000   
mean    5.000000   4.400000   5.400000   5.600000   5.150000   5.050000   
std     1.777047   2.760625   2.583347   2.112619   2.758241   2.762055   
min     2.000000   1.000000   1.000000   1.000000   1.000000   1.000000   
25%     3.000000   2.000000   3.000000   4.750000   2.750000   3.000000   
50%     5.000000   4.000000   5.000000   6.000000   5.500000   5.000000   
75%     6.250000   6.250000   7.250000   6.250000   7.250000   8.000000   
max     8.000000   9.000000   9.000000   9.000000   9.000000   9.000000   

               6         7          8          9  
count  20.000000  20.00000  20.000000  20.000000  
mean    5.000000   4.50000   5.000000   4.350000  
std     2.695025   2.50263   2.883711   2.661124  
min     1.000000   1.00000   1.000000   1.000000  
25%     3.000000   2.00000   2.000000   2.000000  
50%     5.000000   5.00000   5.500000   4.000000  
75%     8.000000   7.00000   7.000000   6.500000  
max     9.000000   8.00000   9.000000   9.000000

In [99]:
#df[['column4','column5']]
type(df[[4,5]])

pandas.core.frame.DataFrame

In [98]:
type(df[4])


pandas.core.series.Series

In [100]:
#df.loc[['row1','row2']]
df.loc[[0,1]]

0  1  2  3  4  5  6  7  8  9
0  6  3  5  6  7  1  8  5  7  1
1  7  1  5  8  9  8  2  6  5  8

In [105]:
df.iloc[3:]

0  1  2  3  4  5  6  7  8  9
3   5  8  4  2  9  5  6  5  7  6
4   4  6  1  8  3  9  3  4  1  8
5   5  4  7  6  2  4  5  8  2  3
6   6  1  5  2  6  8  8  2  3  4
7   6  9  3  9  3  8  8  8  6  3
8   6  8  2  7  2  3  9  5  1  1
9   7  7  9  6  1  5  7  3  7  8
10  3  5  6  6  2  9  1  1  1  2
11  4  2  3  5  9  8  3  1  8  9
12  8  5  9  6  6  5  4  7  9  5
13  7  6  2  1  4  5  1  7  9  4
14  5  2  9  6  8  3  8  2  9  2
15  3  1  8  4  7  1  6  5  2  1
16  3  4  6  6  1  1  4  7  6  4
17  2  9  9  6  5  1  5  1  5  8
18  3  3  5  4  6  5  8  2  1  2
19  7  1  7  6  5  7  3  3  6  5

In [108]:
df.iloc[5:10,3:10]

3  4  5  6  7  8  9
5  6  2  4  5  8  2  3
6  2  6  8  8  2  3  4
7  9  3  8  8  8  6  3
8  7  2  3  9  5  1  1
9  6  1  5  7  3  7  8

In [109]:
np.nan

nan

In [111]:
df.isnull().count()

0    20
1    20
2    20
3    20
4    20
5    20
6    20
7    20
8    20
9    20
dtype: int64

In [112]:
df.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64

In [113]:
df.isna()

0      1      2      3      4      5      6      7      8      9
0   False  False  False  False  False  False  False  False  False  False
1   False  False  False  False  False  False  False  False  False  False
2   False  False  False  False  False  False  False  False  False  False
3   False  False  False  False  False  False  False  False  False  False
4   False  False  False  False  False  False  False  False  False  False
5   False  False  False  False  False  False  False  False  False  False
6   False  False  False  False  False  False  False  False  False  False
7   False  False  False  False  False  False  False  False  False  False
8   False  False  False  False  False  False  False  False  False  False
9   False  False  False  False  False  False  False  False  False  False
10  False  False  False  False  False  False  False  False  False  False
11  False  False  False  False  False  False  False  False  False  False
12  False  False  False  False  False  False  False  False  False  False
13  False  False  False  False  False  False  False  False  False  False
14  False  False  False  False  False  False  False  False  False  False
15  False  False  False  False  False  False  False  False  False  False
16  False  False  False  False  False  False  False  False  False  False
17  False  False  False  False  False  False  False  False  False  False
18  False  False  False  False  False  False  False  False  False  False
19  False  False  False  False  False  False  False  False  False  False

In [114]:
df.isna().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64

In [115]:
df.isna().count()

0    20
1    20
2    20
3    20
4    20
5    20
6    20
7    20
8    20
9    20
dtype: int64

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       20 non-null     int32
 1   1       20 non-null     int32
 2   2       20 non-null     int32
 3   3       20 non-null     int32
 4   4       20 non-null     int32
 5   5       20 non-null     int32
 6   6       20 non-null     int32
 7   7       20 non-null     int32
 8   8       20 non-null     int32
 9   9       20 non-null     int32
dtypes: int32(10)
memory usage: 932.0 bytes


In [117]:
df.describe()

0          1          2          3          4          5  \
count  20.000000  20.000000  20.000000  20.000000  20.000000  20.000000   
mean    5.000000   4.400000   5.400000   5.600000   5.150000   5.050000   
std     1.777047   2.760625   2.583347   2.112619   2.758241   2.762055   
min     2.000000   1.000000   1.000000   1.000000   1.000000   1.000000   
25%     3.000000   2.000000   3.000000   4.750000   2.750000   3.000000   
50%     5.000000   4.000000   5.000000   6.000000   5.500000   5.000000   
75%     6.250000   6.250000   7.250000   6.250000   7.250000   8.000000   
max     8.000000   9.000000   9.000000   9.000000   9.000000   9.000000   

               6         7          8          9  
count  20.000000  20.00000  20.000000  20.000000  
mean    5.000000   4.50000   5.000000   4.350000  
std     2.695025   2.50263   2.883711   2.661124  
min     1.000000   1.00000   1.000000   1.000000  
25%     3.000000   2.00000   2.000000   2.000000  
50%     5.000000   5.00000   5.500000   4.000000  
75%     8.000000   7.00000   7.000000   6.500000  
max     9.000000   8.00000   9.000000   9.000000

In [120]:
arr=np.random.randint(0,10,(10,20))
arr

array([[5, 7, 8, 1, 4, 3, 6, 5, 0, 5, 0, 0, 1, 7, 3, 5, 6, 5, 1, 7],
       [4, 9, 5, 2, 7, 9, 0, 5, 5, 5, 5, 6, 1, 7, 4, 3, 5, 6, 4, 7],
       [3, 4, 8, 4, 4, 2, 8, 1, 9, 8, 8, 8, 7, 4, 1, 6, 0, 3, 0, 7],
       [8, 0, 6, 2, 0, 9, 0, 6, 3, 5, 9, 0, 4, 9, 7, 2, 2, 2, 6, 5],
       [1, 1, 5, 1, 9, 8, 9, 0, 4, 9, 5, 6, 4, 5, 3, 0, 1, 9, 9, 8],
       [2, 5, 3, 4, 2, 6, 1, 7, 2, 8, 5, 2, 5, 2, 7, 0, 7, 0, 9, 1],
       [9, 4, 3, 0, 3, 6, 1, 8, 3, 2, 0, 4, 4, 0, 2, 0, 8, 1, 6, 7],
       [8, 1, 0, 5, 9, 5, 7, 6, 6, 0, 4, 6, 7, 7, 8, 3, 8, 6, 9, 1],
       [8, 2, 7, 2, 2, 2, 7, 2, 1, 4, 9, 3, 3, 9, 4, 1, 4, 1, 5, 1],
       [7, 7, 1, 4, 9, 3, 7, 2, 8, 5, 7, 5, 5, 2, 8, 7, 5, 5, 7, 6]])

In [121]:
df = pd.DataFrame(data=arr)
df


0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  \
0   5   7   8   1   4   3   6   5   0   5   0   0   1   7   3   5   6   5   1   
1   4   9   5   2   7   9   0   5   5   5   5   6   1   7   4   3   5   6   4   
2   3   4   8   4   4   2   8   1   9   8   8   8   7   4   1   6   0   3   0   
3   8   0   6   2   0   9   0   6   3   5   9   0   4   9   7   2   2   2   6   
4   1   1   5   1   9   8   9   0   4   9   5   6   4   5   3   0   1   9   9   
5   2   5   3   4   2   6   1   7   2   8   5   2   5   2   7   0   7   0   9   
6   9   4   3   0   3   6   1   8   3   2   0   4   4   0   2   0   8   1   6   
7   8   1   0   5   9   5   7   6   6   0   4   6   7   7   8   3   8   6   9   
8   8   2   7   2   2   2   7   2   1   4   9   3   3   9   4   1   4   1   5   
9   7   7   1   4   9   3   7   2   8   5   7   5   5   2   8   7   5   5   7   

   19  
0   7  
1   7  
2   7  
3   5  
4   8  
5   1  
6   7  
7   1  
8   1  
9   6

In [126]:
for s in range(0,20):
    print(df[s].value_counts())
    

8    3
5    1
4    1
3    1
1    1
2    1
9    1
7    1
Name: 0, dtype: int64
7    2
4    2
1    2
9    1
0    1
5    1
2    1
Name: 1, dtype: int64
8    2
5    2
3    2
6    1
0    1
7    1
1    1
Name: 2, dtype: int64
2    3
4    3
1    2
0    1
5    1
Name: 3, dtype: int64
9    3
4    2
2    2
7    1
0    1
3    1
Name: 4, dtype: int64
3    2
9    2
2    2
6    2
8    1
5    1
Name: 5, dtype: int64
7    3
0    2
1    2
6    1
8    1
9    1
Name: 6, dtype: int64
5    2
6    2
2    2
1    1
0    1
7    1
8    1
Name: 7, dtype: int64
3    2
0    1
5    1
9    1
4    1
2    1
6    1
1    1
8    1
Name: 8, dtype: int64
5    4
8    2
9    1
2    1
0    1
4    1
Name: 9, dtype: int64
5    3
0    2
9    2
8    1
4    1
7    1
Name: 10, dtype: int64
6    3
0    2
8    1
2    1
4    1
3    1
5    1
Name: 11, dtype: int64
4    3
1    2
7    2
5    2
3    1
Name: 12, dtype: int64
7    3
9    2
2    2
4    1
5    1
0    1
Name: 13, dtype: int64
3    2
4    2
7    2
8    2
1    1
2    1
Name: 14,

In [127]:
for s in range(0,20):
    print(df[s].unique())

[5 4 3 8 1 2 9 7]
[7 9 4 0 1 5 2]
[8 5 6 3 0 7 1]
[1 2 4 0 5]
[4 7 0 9 2 3]
[3 9 2 8 6 5]
[6 0 8 9 1 7]
[5 1 6 0 7 8 2]
[0 5 9 3 4 2 6 1 8]
[5 8 9 2 0 4]
[0 5 8 9 4 7]
[0 6 8 2 4 3 5]
[1 7 4 5 3]
[7 4 9 5 2 0]
[3 4 1 7 2 8]
[5 3 6 2 0 1 7]
[6 5 0 2 1 7 8 4]
[5 6 3 2 9 0 1]
[1 4 0 6 9 5 7]
[7 5 8 1 6]


In [128]:
df[1].unique()

array([7, 9, 4, 0, 1, 5, 2])

In [130]:
df[1].value_counts()

7    2
4    2
1    2
9    1
0    1
5    1
2    1
Name: 1, dtype: int64

In [133]:
type(df[[1]])


pandas.core.frame.DataFrame

In [134]:
type(df[1])

pandas.core.series.Series

In [136]:
df.iloc[3,5]

9

In [137]:
df.loc[[3]]

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  \
3   8   0   6   2   0   9   0   6   3   5   9   0   4   9   7   2   2   2   6   

   19  
3   5